# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ðŸš§ Build - Build sources

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:


env:
  node_version: 20.x
  pnpm_version: 8.x

jobs:
  build-web:
    name: ðŸš§ Build Web
    runs-on: ubuntu-latest

    steps:
      - name: â›™ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: ðŸš§ Build
        uses: ./.github/actions/build
        with:
          node_version: ${{ env.node_version }}
          pnpm_version: ${{ env.pnpm_version }}

  test:
    name: ðŸ§ª Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: â›™ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: ðŸ§± Install
        uses: ./.github/actions/install
        with:
          node_version: ${{ env.node_version }}
          pnpm_version: ${{ env.pnpm_version }}

      - name: ðŸ§ª Unit tests
        run: |
          # ================= ðŸ§ª Unit tests =================
          pnpm run test:unit

  lint:
    name: ðŸ§¹ Lint
    runs-on: ubuntu-latest

    steps:
      - name: â›™ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: ðŸ§± Install
        uses: ./.github/actions/install
        with:
          node_version: ${{ env.node_version }}
          pnpm_version: ${{ env.pnpm_version }}

      - name: ðŸ§¹ Eslint
        run: |
          # =================  ðŸ§¹ Eslint  =================
          pnpm run lint
